# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Flash' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'JFTControllerLoader', :path => '../'

  # Pods for Flash

  target 'FlashTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlashUITests' do
    # Pods for testing
  end

end
